//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CarExplorer.rc
//
#define IDC_MYICON                      2
#define IDD_CONTEXTMENUHANDLER_DIALOG   102
#define IDS_APP_TITLE                   103
#define IDS_MB_APPTITLE                 104
#define IDD_ABOUTBOX                    105
#define IDM_ABOUT                       106
#define IDM_EXIT                        107
#define IDM_FILE_SETFOLDER              108
#define IDI_CONTEXTMENUHANDLER          109
#define IDI_SMALL                       110
#define IDR_MENU                        111
#define IDR_LV_CONTEXTMENU              112
#define IDM_LV_CONTEXTMENU_REPORTVIEW   113
#define IDM_LV_CONTEXTMENU_THUMBNAILSVIEW 114
#define IDM_LV_CONTEXTMENU_ADDTOFAVORITES 115
#define IDM_TV_CONTEXTMENU_DELETE       116
#define IDR_MAINFRAME                   128
#define IDD_EXTRACT                     129
#define IDD_SETTINGS                    130
#define IDB_CLOSED_FOLDER               134
#define IDB_OPEN_FOLDER                 135
#define IDB_DOCUMENT                    136
#define IDB_ARROW_UP                    137
#define IDB_ARROW_DOWN                  138
#define IDD_SETFOLDER                   139
#define IDD_LOAD_IMAGE_SETS             140
#define IDS_PWD_IFFN                    141
#define IDS_PWD_ALT_IFFN                142
#define IDS_IMAGESETSLIST_LOCATION      143
#define IDS_FTP_HOST                    144
#define IDS_FTP_USER                    145
#define IDS_FTP_REPO_DIR                146
#define IDS_MSS_REPO_LOCATION           147
#define IDS_IMAGESETSLIST_ALT_LOCATION  148
#define IDS_NO_FAVORITES                149
#define IDI_TB_FOLDER                   150
#define IDI_TB_DOWNLOAD                 151
#define IDI_TB_SEARCH                   152
#define IDI_TB_FAVORITES                153
#define IDI_TB_SETTINGS                 155
#define IDI_TB_HELP                     156
#define IDD_REGISTER_PRODUCT            157
#define IDI_CLOSED_FOLDER               158
#define IDI_OPEN_FOLDER                 159
#define IDI_DOCUMENT                    160
#define IDI_FAVORITES                   161
#define IDI_FAVORITES_STANDARD          162
#define IDI_FAVORITES_OPENSTANDARD      163
#define IDI_FAVORITES_USER              164
#define IDI_FAVORITES_OPENUSER          165
#define IDI_FAVORITES_GREEN             166
#define IDI_FAVORITES_OPENGREEN         167
#define IDI_FAVORITES_PINK              168
#define IDI_FAVORITES_OPENPINK          169
#define IDB_FAVORITES                   170
#define IDS_MSS_REPO_ALT_LOCATION       171
#define IDI_ARROW_UP                    172
#define IDI_ARROW_DOWN                  173
#define IDC_CURSOR_DAD_DROP             174
#define IDC_CURSOR_DAD_NODROP           175
#define IDS_FOLDER                      176
#define IDS_DOWNLOAD                    177
#define IDS_SEARCH                      178
#define IDS_FAVORITES                   179
#define IDS_VIEW                        180
#define IDS_SETTINGS                    181
#define IDI_TB_VIEW_GREY                182
#define IDS_HELP                        183
#define IDI_TB_VIEW_REPORT              184
#define IDI_TB_VIEW_ICON                185
#define IDB_SEPARATOR_PATTERN           186
#define IDD_PP_GENERAL                  187
#define IDR_TV_CONTEXTMENU              188
#define IDR_TV_CONTEXTMENU_FITEM        189
#define IDR_CUSTOM_GIF                  190
#define IDI_TB_FOLDER_GREYED            191
#define IDI_TB_DOWNLOAD_GREYED          192
#define IDI_TB_FAVORITES_GREYED         193
#define IDI_TB_SEARCH_GREYED            194
#define IDI_CAR_FILE                    195
#define IDI_FAVORITES_ITEM              196
#define IDD_REGISTER_BUY_PRODUCT        197
#define IDI_RBP_BUY                     198
#define IDI_RBP_CLOSE                   199
#define IDI_RBP_CLOSE_GREY              200
#define IDI_RBP_ACTIVATE                201
#define IDI_FAVORITES_GREYED            202
#define IDS_SF_REMOVE_FAVORITES         203
#define IDS_WV_VALIDATION_MSG           204
#define IDR_TV_CONTEXTMENU_FFOLDER      205
#define IDS_IMPORTFAVORITES_ABORTED     206
#define IDS_IMPORTFAVORITES_REPLACE     207
#define IDS_TV_DELETE_ALL_FAVORITES     208
#define IDS_TV_DELETE_FAVORITES_FOLDER  209
#define IDS_TV_CLEAR_FAVORITES_FOLDER   210
#define IDS_TV_DELETE_FAVORITESCARITEM  211
#define IDS_TV_FORBIDDENSYMBOLS         212
#define IDS_TV_ZEROLENTHWARNING         213
#define IDS_TV_FOLDERALREADYEXISTS      214
#define IDD_ADDFOLDER                   215
#define IDI_FAVORITES_RED               216
#define IDI_FAVORITES_OPENRED           217
#define IDC_EDIT                        1000
#define IDC_TOPAREA                     1001
#define IDC_COMBOBOX                    1002
#define IDC_TREEVIEW                    1003
#define IDC_MAIN_LISTVIEW               1004
#define IDC_LISTVIEW                    1005
#define IDC_RIGHT_HOST                  1006
#define IDC_RIGHT_BOTTOM_HOST           1007
#define IDC_BOTTOM_PICTUREVIEW          1008
#define IDC_BOTTOM_LISTVIEW             1009
#define IDC_BUTTON_DESTINATION          1010
#define IDC_SETTINGS_COMBO              1011
#define IDC_SETTINGS_STATIC             1012
#define IDC_SETTINGS_GROUPTBOX          1013
#define IDC_SF_BUTTON                   1015
#define IDC_SF_EDIT                     1016
#define IDC_LIS_LISTBOX1                1017
#define IDC_RP_EDIT_EMAIL               1017
#define IDC_LIS_LISTBOX2                1018
#define IDC_RP_ACTIVATION_CODE          1018
#define IDC_LIS_BUTTON1                 1019
#define IDC_REBAR                       1020
#define IDC_LIS_COMBOBOX                1020
#define IDC_TOOLBAR                     1021
#define IDC_LIS_STATIC_STATUS           1022
#define IDC_RBP_BUTTON_ACTIVATE         1022
#define IDC_LIS_PROGRESS_BAR            1023
#define IDC_RBP_BUTTON_BUY              1023
#define IDC_WELCOME                     1024
#define IDC_RBP_BUTTON_CLOSE            1025
#define IDC_WELCOME_CB_TYPE             1026
#define IDC_WELCOME_CB_PRICERANGE       1027
#define IDC_WELCOME_CB_FUELTYPE         1028
#define IDC_RBP_EDIT_EMAIL              1029
#define IDC_WV_BUTTON                   1030
#define IDC_RBP_ACTIVATION_CODE         1031
#define IDC_IMAGE_WINDOW                1032
#define IDC_RBP_STATIC                  1033
#define IDC_WELCOME_CHECKBOX            1034
#define IDC_SETTINGS_CHECKBOX_SHOWWV    1035
#define IDC_AD_STATIC                   1036
#define IDC_AD_STATIC2                  1037
#define IDC_AD_STATIC3                  1038
#define IDC_AD_STATIC4                  1039
#define IDC_AD_STATIC5                  1040
#define IDS_AD_COPYRIGHT1               1041
#define IDS_AD_COPYRIGHT2               1042
#define IDC_ADDFOLDER_EDIT              1043
#define IDC_WELCOME_CB_YEAR             1044
#define IDC_BUTTON1                     1045
#define IDC_LIS_BUTTON2                 1045
#define ID_FILE_OPEN                    32771
#define IDM_TOOLS_SETTINGS              32772
#define IDM_TOOLS_DOWNLOAD              32776
#define IDM_VIEW_TOOLBAR                32779
#define IDM_VIEW_STATUSBAR              32780
#define IDM_HELP_ACTIVATEPRODUCT        32782
#define ID_TOOLBAR_SEARCH               32783
#define ID_TOOLBAR_FAVORITES            32784
#define ID_TOOLBAR_VIEW                 32786
#define IDM_TOOLS_EXPLORER_FOLDER       32787
#define ID_TV_DELETE                    32788
#define ID_TOOLBAR_HELP                 32789
#define IDM_HELP_WEBSITE                32791
#define IDM_HELP_PRODUCTWEBPAGE         32792
#define IDM_HELP_DONATE                 32793
#define IDM_TV_CONTEXTMENU_FFOLDER_EXPORT 32793
#define IDM_TV_CONTEXTMENU_FFOLDER_IMPORT 32794
#define IDM_TV_CONTEXTMENU_FFOLDER_ADD  32795
#define IDM_TV_CONTEXTMENU_FFOLDER_RENAME 32796
#define IDM_LV_CONTEXTMENU_EXPORT       32798
#define IDM_TV_CONTEXTMENU_FFOLDER_DELETEALL 32800
#define IDM_HELP_DOWNLOADPACK           32801
#define IDM_HELP_MAKECARFILE            32802
#define IDM_HELP_AFFILIATES             32803
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
